name: Nuitka Compile

on:
  workflow_dispatch:  # Add this line to enable manual triggers

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements3.12.txt
    - name: Compile with Nuitka
      run: |
        python -m nuitka --follow-imports --standalone --onefile ./src/main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-executable
        path: main.bin
