# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:  # Add this line to enable manual triggers

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements3.12.txt ]; then pip install -r requirements3.12.txt; fi
#    - name: Lint with Ruff
#      run: |
#        pip install ruff
#        ruff check
#    - name: Verify pytest installation
#      run: pip show pytest
#    - name: Python version
#      run: python --version
    - name: Test with pytest
      run: pytest -v ./tests_ci
